name: Searching portfolio

# Schedule: every 22 minutes (approx 1950 runs/month -> ~1950 minutes)
on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Search
        shell: bash
        run: |
          set -euo pipefail

          # === CONFIGURE THIS ===
          TARGET_URL="www.imrankhan.linkpc.net" 
          # JITTER maximum (in seconds). Keep <=30 to avoid hitting extra billed minute.
          MAX_JITTER=10
          # ======================

          # small list of common browser User-Agents (rotate)
          USER_AGENTS=(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15"
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
          )

          # pick a random user agent
          UA="${USER_AGENTS[$RANDOM % ${#USER_AGENTS[@]}]}"

          # jitter: random sleep 0..MAX_JITTER seconds to avoid predictable pattern
          if [ "$MAX_JITTER" -gt 0 ]; then
            JITTER=$((RANDOM % (MAX_JITTER + 1)))
            echo "Sleeping for ${JITTER}s jitter to randomize timing..."
            sleep "${JITTER}"
          else
            echo "Jitter disabled."
          fi

          # add small random query to vary the URL and avoid identical requests
          RANDSTR=$(head -c 6 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 6 || echo $RANDOM)
          URL="${TARGET_URL}?r=${RANDSTR}"

          echo "Pinging: $URL"
          # perform curl with browser-like headers, follow redirects, retry a couple times if transient error
          curl -sSL --max-time 20 \
            -H "User-Agent: ${UA}" \
            -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
            -H "Accept-Language: en-US,en;q=0.9" \
            -H "Referer: https://www.google.com/" \
            --retry 2 --retry-delay 2 \
            "$URL" > /dev/null || echo "curl failed but continuing"

          echo "Done."
